# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update container image 
        run: |
          ls -al
          cat simple-deployment/nginx-deploy.yaml
          ls -al
          sed -i "/ax7dvcawpc84/c\        image\: me-jeddah-1.ocir\.i/ax7dvcawpc84/portal-qa/switch-admin:3435435" simple-deployment/nginx-deploy.yaml
          cat simple-deployment/nginx-deploy.yaml
      - name: Update changes in GitHub repository
        run:  |
          ls -al
          git config --global user.name 'Your Name' 
          git config --global user.email 'Your Email for GitHub'
          git add .
          git commit -m "test"
          git push
 
